jobs: 5000
use-conda: true
immediate-submit: false
notemp: true
restart-times: 5
jobscript: "slurm-jobscript.sh"
cluster: "/research/home/sreichl/projects/cemm.slurm.sm/slurm-submit.py {dependencies}"
cluster-status: "slurm-status.py"
max-jobs-per-second: 10
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 120
keep-going: true
rerun-incomplete: true
